### ISSUE TITLE
Add background color support

### ISSUE THREAD

**Issue by sepharg** [khalidabuhakmeh/ConsoleTables#21]
It´d be great if you could add a background color to each row based on some property of the item, that could be defined by a delegate.
For example, you add an overload that accepts a function like this

`ConsoleTable.From<Item>(myResults, (item) => { item.Value > 50 ? RowBackground.Red : RowBackground.Green }).Write();`

In this case rows that contain items with value bigger than 50 will be printed out with a red background, the rest with a green one.

**Comment by sepharg** [comment]
any thoughts on this @khalidabuhakmeh ? 
if you're not able to add this maybe i can collaborate and add it myself if that's ok for you?

**Comment by kiran94** [comment]
I would also be interested in something like this. It would also be good to have foreground colour support.

**Comment by khalidabuhakmeh** [comment]
Feel free to submit a PR. Most changes are welcome and I'll help where I can 😁

**Comment by CerebralMischief** [comment]
> 
> 
> Feel free to submit a PR. Most changes are welcome, and I'll help where I can 😁

Unfortunately, people are happy to use code other people wrote, but contributing to it is asking far too much.  😁

**Comment by khalidabuhakmeh** [comment]
It's cool, I know folks are busy. 

I recommend folks check out https://github.com/spectresystems/spectre.console. 

ConsoleTables was a hobby project. Patrik has definitely done a great job and I've contributed a few ideas there. .NET OSS for the win. :)
