### ISSUE TITLE
Add support for hyperlinks

### ISSUE THREAD

**Issue by scottt732** [khalidabuhakmeh/ConsoleTables#52]
Some terminals support ANSI-style sequences for hyperlinks (separate text & URL).  It would be awesome if we could setup columns backed by 2 fields of information (one for link, one for text).
https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda

**Comment by Yuan-Quan** [comment]
As far as I know: 
If the text is a URL, path to file, terminal emulator will make it clickable automatically.  
  
If you want a hyperlink like [this](https://github.com/khalidabuhakmeh/ConsoleTables), there are two ways: 
1. Some sort of markup language interrupted by shell/terminal. Highly rely on shell/terminal, not recommended.
2. Get mouse position and action, implement the clickable stuff yourself.

**Comment by khalidabuhakmeh** [comment]
This might be out of scope for this project. If you want to try, I'd be happy to accept a PR.
