### ISSUE TITLE
Table will went wrong if some chars' width is two. (如果某些字符的宽度是2, 表格将出错)

### ISSUE THREAD

**Issue by SlimeNull** [khalidabuhakmeh/ConsoleTables#55]
![image](https://user-images.githubusercontent.com/69663231/109021356-c5a63000-76f5-11eb-8c9f-92b0616d5c7a.png)
![image](https://user-images.githubusercontent.com/69663231/109021401-ce970180-76f5-11eb-813f-f0d0b35d607c.png)

English:
Clearly, if a char which width is two, this current row will move right...
Also, if you want to calculate the width of a string in the console, see this repository: [Null.ConsoleEx](https://github.com/SlimeNull/Null.ConsoleEx)

using namspace Null.ConsoleEx, and call this method: ConsoleEx.GetStringDisplayLength(string str);

Chinese :
下面是中文:
显然, 如果一个字符的宽度是2, 当前的这一行就会向右移动...
对了, 如果你想计算字符串在控制台中的宽度, 看看这个仓库吧: [Null.ConsoleEx](https://github.com/SlimeNull/Null.ConsoleEx)
using Null.ConsoleEx 命名空间, 然后调用这个方法: ConsoleEx.GetStringDisplayLength(string str);

**Comment by lx1587496147** [comment]
哈哈哈Null你跑这里来干啥[滑稽]

**Comment by lx1587496147** [comment]
还有并不是宽度是2，而是其他字符（的宽度）是ASCII字符的宽度的两倍

**Comment by lx1587496147** [comment]
这个其实和Windows的字体渲染有点关系

**Comment by lx1587496147** [comment]
很多软件也有这种问题

**Comment by lx1587496147** [comment]
比如ssh（貌似是ash的问题）

**Comment by lx1587496147** [comment]
还有如果你有解决方案应该fork代码然后建立一个Pull Request

**Comment by lx1587496147** [comment]
发一个Issue基本没法解决问题

**Comment by SlimeNull** [comment]
没办法解决就不解决了, 反正这个我用不到

**Comment by 1610450962** [comment]
At present, the problem is that the table will be deformed by inputting some characters

**Comment by khalidabuhakmeh** [comment]
I believe the latest release `2.5.0` addresses this issue.
