### ISSUE TITLE
Multiline

### ISSUE THREAD

**Issue by mattkbach** [khalidabuhakmeh/ConsoleTables#60]
Hello

Just wondering if it is possible to use a newline within a row/column to create a multiline effect. Currently when I use \n it creates a whole new line and messes up the table format. 

Thanks!

**Comment by khalidabuhakmeh** [comment]
I don't think this library supports it, but it would be a fun thing to try and attempt if you want to take a crack at it.

**Comment by PolarGoose** [comment]
I have encountered the same use case.
Unfortunately, the library doesn't support it.

**Comment by khalidabuhakmeh** [comment]
I recommend you use Spectre Console. That project is excellent and has figured out how to redraw when the console width changes.

This project was always meant to be a fun experiment in writing and publishing a NuGet package.
