### ISSUE TITLE
Special Characters break column alignment

### ISSUE THREAD

**Issue by hbre** [khalidabuhakmeh/ConsoleTables#68]
Special Characters like `äöüßé` break the column alignment.

Left output is expected but instead right output is produced:

<img width="443" alt="Bildschirmfoto 2023-11-06 um 10 50 23" src="https://github.com/khalidabuhakmeh/ConsoleTables/assets/898832/73d19457-308d-4e7a-b6b2-af83927c3c67">

Expected Output would be
```
--------------  
| Name | Age |
-------------- 
| René |  59 |
-------------- 
| Otto |  52 |
-------------- 
```

but instead
```
--------------- 
| Name  | Age |
--------------- 
| René |  59 |
--------------- 
| Otto  |  52 |
--------------- 
```

**Comment by oahsiao** [comment]
I got the same fail for Chinese 中文測試 
 -----------------------
 | 中文測試  | two | three |
 -----------------------
 | 1     | 2   | 3     |
 -----------------------

**Comment by SIITON** [comment]
Try increasing the value 127. Had the same issue with 'åäö'. 
![image](https://github.com/user-attachments/assets/b95ad1eb-c032-4a3c-aace-6858f5a3bf9b)

**Comment by khalidabuhakmeh** [comment]
Deploying the change to NuGet now. Thank you for the fix.
