### ISSUE TITLE
Plz update Nuget package 

### ISSUE THREAD

**Issue by ostelaymetaule** [khalidabuhakmeh/ConsoleTables#7]
Hello,
thanx for the great tool! But could you please update the nuget package to the version that is .net4.0 compatible?

>Install-Package : Could not install package 'ConsoleTables 1.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0', but the package does not contain any assembly references or content files that are compatible
 with that framework.

**Comment by khalidabuhakmeh** [comment]
I believe this targets 4.0 now in nuget. Closing this issue.
