### ISSUE TITLE
String.Format throws exception

### ISSUE THREAD

**Issue by FabioCZ** [khalidabuhakmeh/ConsoleTables#8]
On my setup (Mono/.Net 4.5), String.Format throws exception (incorrect input string format).

Seems to be caused by spaces in the alignment component 

[ConsoleTable.cs#69](https://github.com/khalidabuhakmeh/ConsoleTables/blob/master/ConsoleTables.Core/ConsoleTable.cs#L69) produces those spaces (e.g. "{0, -1 }" instead of "{0,-1}"). With spaces removed, everything seems to work alright.

**Comment by khalidabuhakmeh** [comment]
PR me the fix and I'll merge it in 😀

**Comment by FabioCZ** [comment]
Would do that, but seems like I don't have push permissions for this repo.

**Comment by khalidabuhakmeh** [comment]
I just pushed 1.1.1 to fix this issue. Try it out.
